language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - build-essential

install:
    - git submodule init
    - git submodule update
    - pip install -r requirements.txt

script:
    - flake8 pypapi
    - python setup.py build

